### ISSUE TITLE
Option "default game" only allows Fallout 4, not Skyrim

### ISSUE THREAD

**Issue by greyspammer** [Gawdl3y/atom-build-papyrus#2]
In the settings, there's an option to set the default game. But it can't be set to Skyrim, because the dropdown list only contains Fallout 4. Both games are installed, compiler paths are set correctly.

Not sure what sense there is in an option that can have only one possible value.

**Comment by Gawdl3y** [comment]
The setting is for the default game when using project files. Skyrim does not support project files. The setting is there for any future games.
